{
 "title": "Tinkoff",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "account", "query": { "query": "label_values(account)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{type=\"priceTotal\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Total Yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{type=\"yieldTotal\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{type=\"priceTotal\"})",
     "legendFormat": "price"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{type=\"yieldTotal\"})",
     "legendFormat": "yield"
    }
   ]
  },
  { "title": "$account", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "account" },
  {
   "title": "Account Price",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{account=\"$account\", type=\"priceTotal\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Account Yield",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "currencyRUB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{account=\"$account\", type=\"yieldTotal\"})",
     "legendFormat": " "
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{account=\"$account\", type=\"priceTotal\"})",
     "legendFormat": "price"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "sum(tin_invest_portfolio{account=\"$account\", type=\"yieldTotal\"})",
     "legendFormat": "yield"
    }
   ]
  },
  {
   "title": "Instrument Price Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_portfolio{account=\"$account\", type=\"priceTotal\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Yield Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_portfolio{account=\"$account\", type=\"yieldTotal\"} != 0",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Price One",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "₽" } },
   "targets": [
    {
     "expr": "tin_invest_portfolio{account=\"$account\", type=\"priceOne\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  },
  {
   "title": "Instrument Quantity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "tin_invest_portfolio{account=\"$account\", type=\"quantity\"}",
     "legendFormat": "{{instrument}}"
    }
   ]
  }
 ]
}