name: SSH

on:
  push:
    branches:
      - master

jobs:
  ssh:
    name: SSH
    environment: vds
    runs-on: ubuntu-latest
    steps:
      - name: Run commands
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.KEY }}
          script: |
            cd ~/git/tin-invest-prom-exporter
            gpl
            npm run setup
            screstart tin-invest-exporter.service
