name: SSH

on:
  push:
    branches:
      - master

jobs:
  ssh:
    name: SSH
    environment: vds
    runs-on: ubuntu-latest
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/vds.key
          chmod 600 ~/.ssh/vds.key
          cat >>~/.ssh/config <<END
          Host vds
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/vds.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT }}

      - name: Run command
        run: ssh vds 'cd ~/git/tin-invest-prom-exporter && git pull'
